
import Head from 'next/head';
import Image from 'next/image';

import styles from '@/styles/pages/Home.module.scss';

export default function Home(){
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className={styles.title}>Hallo</h1>
      </main>
    </>
  )
}
